### ISSUE TITLE
Text search results hidden in panel

### ISSUE THREAD

**Issue by ColmDC** [SolidarityEconomyAssociation/coopsuk#18]
**Describe the bug**
Conducting a text search filters the co-ops that appear in the map, but no search results appear in the panel.

**To Reproduce**
1. [Go to '...](https://dev.maps.solidarityeconomy.coop/temp/coopsuk/)'
2. Open the search panel
3. Search for Apple
4. 16 odd co-ops are left in the map, but no results appear in the panel

**Expected behavior**
We should see al least 16 coops listed at the bottom of the panel

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox
 - mykomap@3.0.4_b522fc2-modified-dev

**Additional context**
This is not a problem in OBO with same build, so it may only be apparent if there are no filter drop down options available in the panel.

**Comment by wu-lee** [comment]
I see an exception in the debug console: 

> filterableFields contains cukSector, which is not a valid vocab field

At some point post v3.0.4 I've added an explicit check to disallow non-vocab fields in the directory. This means cukSector doesn't work.

Should I have? Hm. Maybe not - the intent was to fail early and explicitly rather than silently somewhere else. But this may have clobbered the use of them directories too. 

However, this is related to the ad-hoc vocabs filter issue https://github.com/digitalcommons/mykomap/issues/201 - 

So I could remove the check. But the above issue will also fix this.

**Comment by wu-lee** [comment]
Update: note that coopsuk's `dev` branch is on 3.0.4, which works.

I'm just updating the hook-runner to rebuild this case, as it was on 3.0.2.

**Comment by wu-lee** [comment]
> I'm just updating the hook-runner to rebuild this case, as it was on 3.0.2.

Done

**Comment by ColmDC** [comment]
So I think we can close this?
